import { describe, it, expect } from "vitest";
import { assembleLiquidFile } from "../ssg/liquid-assembler";
import { getOutputPath } from "../ssg/liquid-paths";
import type { SSGEntry } from "../types";

function makeEntry(overrides: Partial<SSGEntry> = {}): SSGEntry {
  return {
    filePath: "/app/frontend/sections/TestSection.tsx",
    componentName: "TestSection",
    kebabName: "test-section",
    targetType: "section",
    meta: {
      name: "Test Section",
      type: "section",
      tag: "section",
      class: "test-class",
      settings: [],
      presets: [],
    },
    ...overrides,
  };
}

const defaultOptions = {
  prefix: { template: "page.react-", section: "react-", block: "react-", snippet: "react-" },
  outputName: "",
  buildDir: "assets",
};

describe("assembleLiquidFile", () => {
  it("generates data-ssg-liquid bridge with tracked expressions", () => {
    const html = "<h1>{{ section.settings.title }}</h1>";
    const entry = makeEntry();
    const result = assembleLiquidFile(
      html,
      entry,
      null,
      { inline: [], snippets: [] },
      defaultOptions,
      ["section.settings.title", "section.settings.description"],
    );

    expect(result).toContain('data-ssg-liquid');
    expect(result).toContain('"section.settings.title"');
    expect(result).toContain("{{ section.settings.title | json }}");
    expect(result).toContain('"section.settings.description"');
    expect(result).toContain("{{ section.settings.description | json }}");
  });

  it("does not generate bridge when no expressions tracked", () => {
    const html = "<div>Static content</div>";
    const entry = makeEntry();
    const result = assembleLiquidFile(html, entry, null, { inline: [], snippets: [] }, defaultOptions, []);

    expect(result).not.toContain("data-ssg-liquid");
  });

  it("generates valid JSON structure in bridge", () => {
    const html = "<div></div>";
    const entry = makeEntry();
    const result = assembleLiquidFile(
      html,
      entry,
      null,
      { inline: [], snippets: [] },
      defaultOptions,
      ["section.settings.title"],
    );

    expect(result).toMatch(/\{\s*"section\.settings\.title":\s*\{\{\s*section\.settings\.title\s*\|\s*json\s*\}\}\s*\}/);
  });

  it("JSON bridge has no trailing comma after last entry", () => {
    const entry = makeEntry();
    const result = assembleLiquidFile(
      "<div></div>",
      entry,
      null,
      { inline: [], snippets: [] },
      defaultOptions,
      ["section.settings.title", "section.settings.description"],
    );

    expect(result).not.toMatch(/,(\s*)\}/);
    expect(result).toContain('"section.settings.title":');
    expect(result).toContain('"section.settings.description":');
  });

  it("single expression bridge has no trailing comma", () => {
    const entry = makeEntry();
    const result = assembleLiquidFile(
      "<div></div>",
      entry,
      null,
      { inline: [], snippets: [] },
      defaultOptions,
      ["section.settings.title"],
    );

    expect(result).toMatch(/\|\s*json\s*\}\}\s*\n\s*\}/);
  });

  it("includes all wrappers: component ID, hydrate container, disclaimer", () => {
    const entry = makeEntry();
    const result = assembleLiquidFile("<div>test</div>", entry, null, { inline: [], snippets: [] }, defaultOptions, []);

    expect(result).toContain("IMPORTANT: This file is automatically generated");
    expect(result).toContain('data-ssg-component="test-section"');
    expect(result).toContain("data-ssg-hydrate");
    expect(result).toContain("{% schema %}");
  });

  it("generates block template with correct attributes", () => {
    const entry = makeEntry({
      targetType: "block",
      meta: { name: "Test Block", type: "block", tag: "div", class: "", settings: [], presets: [], blocks: [] },
    });
    const result = assembleLiquidFile("<div></div>", entry, null, { inline: [], snippets: [] }, defaultOptions, ["block.settings.color"]);

    expect(result).toContain('id="{{ block.id }}"');
    expect(result).toContain("{{ block.shopify_attributes }}");
    expect(result).toContain("{%- doc -%}");
    expect(result).toContain("theme-block");
    expect(result).toContain("block.settings.color");
  });

  it("generates snippet template", () => {
    const entry = makeEntry({
      targetType: "snippet",
      meta: { name: "Test Snippet", type: "snippet", tag: "div", class: "", presets: [] },
    });
    const result = assembleLiquidFile("<p></p>", entry, null, { inline: [], snippets: [] }, defaultOptions, ["product_title"]);

    expect(result).not.toContain("{% schema %}");
    expect(result).toContain("product_title");
  });

  it("includes content_for 'blocks' when entry has blocks", () => {
    const entry = makeEntry({
      meta: {
        ...makeEntry().meta,
        blocks: [{ type: "child-block" }, { type: "other-block" }],
        max_blocks: 4,
      },
    });
    const result = assembleLiquidFile("<div></div>", entry, null, { inline: [], snippets: [] }, defaultOptions, []);

    expect(result).toContain("{% content_for 'blocks' %}");
  });

  it("includes CSS inline", () => {
    const entry = makeEntry();
    const result = assembleLiquidFile("<div></div>", entry, null, { inline: [".foo{color:red}"], snippets: [] }, defaultOptions, []);

    expect(result).toContain("{% stylesheet %}");
    expect(result).toContain(".foo{color:red}");
  });

  it("includes CSS snippets", () => {
    const entry = makeEntry();
    const result = assembleLiquidFile("<div></div>", entry, null, { inline: [], snippets: ["css-shared"] }, defaultOptions, []);

    expect(result).toContain("{% render 'css-shared' %}");
  });

  it("includes script asset tag", () => {
    const entry = makeEntry();
    const result = assembleLiquidFile("<div></div>", entry, "test-section.js", { inline: [], snippets: [] }, defaultOptions, []);

    expect(result).toContain('<script type="module"');
    expect(result).toContain("test-section.js");
  });
});

describe("getOutputPath", () => {
  const themeRoot = "/app/theme";

  it("returns section path", () => {
    const entry = makeEntry();
    const p = getOutputPath(entry, {
      prefix: defaultOptions.prefix,
      outputName: undefined,
      themeRoot,
    });
    expect(p).toBe("/app/theme/sections/react-test-section.liquid");
  });

  it("returns block path", () => {
    const entry = makeEntry({
      targetType: "block",
      meta: { ...makeEntry().meta, type: "block" },
    });
    const p = getOutputPath(entry, {
      prefix: defaultOptions.prefix,
      outputName: undefined,
      themeRoot,
    });
    expect(p).toBe("/app/theme/blocks/react-test-section.liquid");
  });

  it("returns snippet path", () => {
    const entry = makeEntry({
      targetType: "snippet",
      meta: { ...makeEntry().meta, type: "snippet" },
    });
    const p = getOutputPath(entry, {
      prefix: defaultOptions.prefix,
      outputName: undefined,
      themeRoot,
    });
    expect(p).toBe("/app/theme/snippets/react-test-section.liquid");
  });

  it("uses custom outputName template", () => {
    const entry = makeEntry();
    const p = getOutputPath(entry, {
      prefix: defaultOptions.prefix,
      outputName: "{kebab}",
      themeRoot,
    });
    expect(p).toContain("test-section.liquid");
    expect(p).not.toContain("react-");
  });
});

describe("assembleLiquidFile — bridge isolation", () => {
  it("section and block entries get independent bridges", () => {
    const sectionHtml = "<div>section content</div>";
    const blockHtml = "<span>block content</span>";

    const sectionEntry = makeEntry({
      kebabName: "parent-section",
      meta: { ...makeEntry().meta, blocks: [{ type: "child" }] },
    });
    const blockEntry = makeEntry({
      targetType: "block",
      kebabName: "child-block",
      meta: { name: "Child", type: "block", tag: "div", class: "", settings: [], presets: [], blocks: [] },
    });

    const sectionResult = assembleLiquidFile(
      sectionHtml, sectionEntry, null, { inline: [], snippets: [] }, defaultOptions,
      ["section.settings.title"],
    );
    const blockResult = assembleLiquidFile(
      blockHtml, blockEntry, null, { inline: [], snippets: [] }, defaultOptions,
      ["block.settings.color"],
    );

    expect(sectionResult).toContain("section.settings.title");
    expect(sectionResult).not.toContain("block.settings.color");

    expect(blockResult).toContain("block.settings.color");
    expect(blockResult).not.toContain("section.settings.title");
  });
});
