import type { SSGEntry } from "../../types";
import { generateSchema } from "./schema-gen";

const DISCLAIMER =
  "{% comment %}\n  IMPORTANT: This file is automatically generated by vite-plugin-shopify.\n  Do not attempt to modify this file directly, as any changes will be overwritten by the next build.\n{% endcomment %}\n";

interface AssembleOptions {
  prefix: { template: string; section: string; block: string; snippet: string };
  outputName?: string;
  buildDir: string;
}

export function assembleLiquidFile(
  html: string,
  entry: SSGEntry,
  scriptAsset: string | null,
  cssContents: { inline: string[]; snippets: string[] },
  options: AssembleOptions,
  accessedSettings: string[] = [],
  accessedParams: string[] = [],
): string {
  const type = entry.meta.type ?? entry.targetType;
  const parts = [DISCLAIMER];

  switch (type) {
    case "template":
      parts.push(html);
      break;
    case "section":
      parts.push(...buildSection(html, entry, accessedSettings));
      break;
    case "block":
      parts.push(...buildBlock(html, entry, accessedSettings, accessedParams));
      break;
    case "snippet":
      parts.push(...buildSnippet(html, entry, accessedParams));
      break;
    default:
      parts.push(...buildSection(html, entry, accessedSettings));
      break;
  }

  for (const snippet of cssContents.snippets) {
    parts.push("", `{% render '${snippet}' %}`);
  }

  if (cssContents.inline.length > 0) {
    parts.push(
      "",
      "{% stylesheet %}",
      ...cssContents.inline.map((c) => c.trim()),
      "{% endstylesheet %}",
    );
  }

  if (scriptAsset) {
    const assetPath = getAssetRelativePath(options.buildDir, scriptAsset);
    parts.push(
      "",
      `<script type="module" src="{{ '${assetPath}' | asset_url }}"></script>`,
    );
  }

  if (type !== "snippet") {
    parts.push(generateSchema(entry.meta));
  }

  return parts.join("\n") + "\n";
}

const hasBlocks = (entry: SSGEntry): boolean =>
  !!entry.meta.blocks && entry.meta.blocks.length > 0;

function buildSettingsBridge(prefix: string, keys: string[]): string {
  if (keys.length === 0) return "";
  const entries = keys
    .map((k) => `    "${k}": {{ ${prefix}.settings.${k} | json }}`)
    .join(",\n");
  return `  <script type="application/json" data-ssg-props>\n  {\n${entries}\n  }\n  </script>`;
}

function buildParamsBridge(params: string[], accessedParams?: string[]): string {
  const keys = accessedParams && accessedParams.length > 0 ? accessedParams : params;
  if (keys.length === 0) return "";
  const entries = keys
    .map((p) => `    "${p}": {{ ${p} | json }}`)
    .join(",\n");
  return `  <script type="application/json" data-ssg-params>\n  {\n${entries}\n  }\n  </script>`;
}

function buildSection(html: string, entry: SSGEntry, accessedSettings: string[]): string[] {
  const tag = entry.meta.tag ?? "div";
  const cls = entry.meta.class ?? "";

  const lines: string[] = [
    "",
    `<${tag}`,
    `  id="{{ section.id }}"`,
    `  data-section-id="{{ section.id }}"`,
    `  data-ssg-component="${entry.kebabName}"`,
  ];
  if (cls) lines.push(`  class="${cls}"`);
  lines.push(`>`);
  const settingsBridge = buildSettingsBridge("section", accessedSettings);
  if (settingsBridge) lines.push(settingsBridge);
  lines.push(
    `  <div data-ssg-hydrate>`,
    `    ${html}`,
    `  </div>`,
  );
  if (hasBlocks(entry)) lines.push(`  {% content_for 'blocks' %}`);
  lines.push(`</${tag}>`);
  return lines;
}

function buildBlock(html: string, entry: SSGEntry, accessedSettings: string[], accessedParams: string[]): string[] {
  const tag = entry.meta.tag ?? "div";
  const cls = entry.meta.class ?? "";

  const lines: string[] = [
    "",
    `{%- doc -%}`,
    `  @name ${entry.meta.name}`,
    `  @context theme-block`,
    `{%- enddoc -%}`,
    "",
    `<${tag}`,
    `  id="{{ block.id }}"`,
    `  data-section-id="{{ section.id }}"`,
    `  data-ssg-component="${entry.kebabName}"`,
  ];
  if (cls) lines.push(`  class="${cls}"`);
  lines.push(
    `  {{ block.shopify_attributes }}`,
    `>`,
  );
  const settingsBridge = buildSettingsBridge("block", accessedSettings);
  if (settingsBridge) lines.push(settingsBridge);
  const paramsBridge = buildParamsBridge(entry.meta.params || [], accessedParams);
  if (paramsBridge) lines.push(paramsBridge);
  lines.push(
    `  <div data-ssg-hydrate>`,
    `    ${html}`,
    `  </div>`,
  );
  if (hasBlocks(entry)) lines.push(`  {% content_for 'blocks' %}`);
  lines.push(`</${tag}>`);
  return lines;
}

function buildSnippet(html: string, entry: SSGEntry, accessedParams: string[]): string[] {
  const lines: string[] = [
    "",
    `<div data-ssg-component="${entry.kebabName}">`,
  ];
  const paramsBridge = buildParamsBridge(entry.meta.params || [], accessedParams);
  if (paramsBridge) lines.push(paramsBridge);
  lines.push(
    `  <div data-ssg-hydrate>`,
    `    ${html}`,
    `  </div>`,
    `</div>`,
  );
  return lines;
}

export function getOutputPath(
  entry: SSGEntry,
  options: {
    prefix: { template: string; section: string; block: string; snippet: string };
    outputName?: string;
    themeRoot: string;
  },
): string {
  const type = entry.meta.type ?? entry.targetType;
  const dirName = typeToDir(type);
  const fileName = resolveFileName(entry, type, options);
  return path.join(options.themeRoot, dirName, fileName);
}

function typeToDir(type: string): string {
  if (type === "snippet") return "snippets";
  if (type === "block") return "blocks";
  return `${type}s`;
}

import path from "node:path";

function getAssetRelativePath(buildDir: string, filename: string): string {
  if (!buildDir.startsWith("assets/")) return filename;
  const prefix = buildDir.slice("assets/".length);
  return prefix ? `${prefix}/${filename}` : filename;
}

function resolveFileName(
  entry: SSGEntry,
  type: string,
  options: {
    prefix: { template: string; section: string; block: string; snippet: string };
    outputName?: string;
  },
): string {
  if (options.outputName) {
    return (
      options.outputName
        .replace(/\{type\}/g, type)
        .replace(/\{kebab\}/g, entry.kebabName)
        .replace(/\{pascal\}/g, entry.componentName)
        .replace(/\{target\}/g, entry.targetType) + ".liquid"
    );
  }

  const prefix = options.prefix[type as keyof typeof options.prefix] ?? "react-";
  return `${prefix}${entry.kebabName}.liquid`;
}
