import type { SSGEntry } from "../types/ssg";
import { normalizePath } from "vite";

export function generateEntryModule(entry: SSGEntry, componentRel: string): string {
  const { kebabName } = entry;
  return [
    `import { createElement } from 'react'`,
    `import Component from '~/${componentRel}'`,
    `import { hydrateRoot } from 'react-dom/client'`,
    `import { LiquidDataProvider } from 'vite-plugin-react-shopify/runtime'`,
    ``,
    `const SELECTOR = '[data-ssg-component="${kebabName}"]'`,
    `const roots = new Map()`,
    ``,
    `function readLiquidData(el) {`,
    `  const script = el.querySelector(':scope > script[data-ssg-liquid]')`,
    `  if (!script) return {}`,
    `  try { return JSON.parse(script.textContent || '{}') } catch { return {} }`,
    `}`,
    ``,
    `function hydrate(el) {`,
    `  const h = el.querySelector(':scope > [data-ssg-hydrate]') || (el.matches('[data-ssg-hydrate]') ? el : null)`,
    `  if (!h || roots.has(h)) return`,
    `  const liquidData = readLiquidData(el)`,
    `  roots.set(h, hydrateRoot(h, createElement(LiquidDataProvider, { value: liquidData }, createElement(Component))))`,
    `}`,
    ``,
    `function unmount(el) {`,
    `  const h = el.querySelector(':scope > [data-ssg-hydrate]') || (el.matches('[data-ssg-hydrate]') ? el : null)`,
    `  if (h && roots.has(h)) { roots.get(h).unmount(); roots.delete(h) }`,
    `}`,
    ``,
    `function scan(target) {`,
    `  if (target.matches?.(SELECTOR)) hydrate(target)`,
    `  target.querySelectorAll(SELECTOR).forEach(hydrate)`,
    `}`,
    ``,
    `function sweep(target) {`,
    `  if (target.matches?.(SELECTOR)) unmount(target)`,
    `  target.querySelectorAll(SELECTOR).forEach(unmount)`,
    `}`,
    ``,
    `scan(document)`,
    ``,
    `document.addEventListener('shopify:section:load', (e) => {`,
    `  scan(e.target)`,
    `})`,
    ``,
    `document.addEventListener('shopify:section:unload', (e) => {`,
    `  sweep(e.target)`,
    `})`,
  ].join("\n");
}
