import fs from "node:fs";
import path from "node:path";
import { Plugin, Manifest } from "vite";
import type { ResolvedOptions } from "../options";
import { compileAllEntries } from "./compiler";

export default function shopifySSG(options: ResolvedOptions): Plugin {
  return {
    name: "vite-plugin-shopify:ssg",
    enforce: "post",

    config() {
      return {};
    },

    async closeBundle() {
      const manifestPath = path.resolve(
        options.themeRoot,
        "assets",
        ".vite",
        "manifest.json",
      );

      if (!fs.existsSync(manifestPath)) {
        console.warn("[vite-plugin-shopify] No manifest.json found, skipping SSG");
        return;
      }

      const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf-8")) as Manifest;

      console.log("[vite-plugin-shopify] Starting SSG compilation...");
      await compileAllEntries(options, manifest);
      console.log("[vite-plugin-shopify] SSG compilation complete");

      writeImportMapSnippet(options);
    },

    resolveId(id) {
      if (id === "vite-plugin-shopify/runtime") {
        return "\0vite-plugin-shopify:runtime";
      }
    },

    load(id) {
      if (id === "\0vite-plugin-shopify:runtime") {
        return `export { Liquid } from 'vite-plugin-shopify/runtime/Liquid'`;
      }
    },
  };
}

function writeImportMapSnippet(options: ResolvedOptions): void {
  const snippetPath = path.resolve(
    options.themeRoot,
    "snippets",
    options.snippetFile,
  );

  const content = [
    "{% comment %}IMPORTANT: Auto-generated by vite-plugin-react-shopify{% endcomment %}",
    '<script type="importmap">',
    "{",
    '  "imports": {',
    `    "react": "${options.importMap.react}",`,
    `    "react-dom/client": "${options.importMap.reactDomClient}"`,
    "  }",
    "}",
    "</script>",
    "",
  ].join("\n");

  const dir = path.dirname(snippetPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(snippetPath, content);
}

export { compileAllEntries } from "./compiler";
