import fs from "node:fs";
import path from "node:path";
import { Plugin, Manifest } from "vite";
import type { ResolvedOptions } from "../core/options";
import { logger } from "../core/logger";
import { compileAllEntries } from "./compiler";

const log = logger("ssg");

export default function shopifySSG(options: ResolvedOptions): Plugin {
  return {
    name: "vite-plugin-shopify:ssg",
    enforce: "post",

    config() {
      return {};
    },

    async closeBundle() {
      const manifestPath = path.resolve(
        options.themeRoot,
        options.buildDir,
        ".vite",
        "manifest.json",
      );

      if (!fs.existsSync(manifestPath)) {
        log.warn("No manifest.json found, skipping SSG");
        return;
      }

      log.debug("reading manifest from %s", manifestPath);
      const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf-8")) as Manifest;

      log.info("Starting SSG compilation...");
      await compileAllEntries(options, manifest);
      log.info("SSG compilation complete");

      writeImportMapSnippet(options);
      log.debug("wrote import map snippet");
    },

    resolveId(id) {
      if (id === "vite-plugin-shopify/runtime") {
        return "\0vite-plugin-shopify:runtime";
      }
    },

    load(id) {
      if (id === "\0vite-plugin-shopify:runtime") {
        const exports = [
          `export { LiquidDataProvider, LiquidDataContext } from 'vite-plugin-shopify/runtime'`,
          `export { useLiquidValue, useLiquidValues, useSectionSettings, useBlockSettings, useSnippetParams, useBlockParams } from 'vite-plugin-shopify/runtime'`,
        ];
        return exports.join("\n");
      }
    },
  };
}

function writeImportMapSnippet(options: ResolvedOptions): void {
  const snippetPath = path.resolve(
    options.themeRoot,
    "snippets",
    options.snippetFile,
  );

  const content = [
    "{% comment %}IMPORTANT: Auto-generated by vite-plugin-react-shopify{% endcomment %}",
    '<script type="importmap">',
    "{",
    '  "imports": {',
    `    "react": "${options.importMap.react}",`,
    `    "react-dom/client": "${options.importMap.reactDomClient}"`,
    "  }",
    "}",
    "</script>",
    "",
  ].join("\n");

  const dir = path.dirname(snippetPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(snippetPath, content);
}
