import type { SSGEntry } from "../types";
import { generateSchema } from "./schema-gen";

const DISCLAIMER =
  "{% comment %}\n  IMPORTANT: This file is automatically generated by vite-plugin-shopify.\n  Do not attempt to modify this file directly, as any changes will be overwritten by the next build.\n{% endcomment %}\n";

interface AssembleOptions {
  prefix: { template: string; section: string; block: string };
  outputName?: string;
}

export function assembleLiquidFile(
  html: string,
  entry: SSGEntry,
  scriptAsset: string | null,
  options: AssembleOptions,
): string {
  const type = entry.meta.type ?? entry.targetType;
  const parts = [DISCLAIMER];

  switch (type) {
    case "template":
      parts.push(html);
      break;
    case "section":
      parts.push(...buildSection(html, entry));
      break;
    case "block":
      parts.push(...buildBlock(html, entry));
      break;
    default:
      parts.push(...buildSection(html, entry));
      break;
  }

  if (scriptAsset) {
    parts.push(
      "",
      `<script type="module" src="{{ '${scriptAsset}' | asset_url }}"></script>`,
    );
  }

  parts.push(generateSchema(entry.meta));

  return parts.join("\n") + "\n";
}

function buildSection(html: string, entry: SSGEntry): string[] {
  const tag = entry.meta.tag ?? "div";
  const cls = entry.meta.class ?? "";

  return [
    "",
    "{% liquid",
    `  assign el_id = 'shopify-' | append: section.id`,
    "%}",
    "",
    `<${tag}`,
    `  id="{{ el_id }}"`,
    `  data-section-id="{{ section.id }}"`,
    `  data-ssg-component="${entry.kebabName}"`,
    cls ? `  class="${cls}"` : "",
    `>`,
    `  <div data-ssg-hydrate>`,
    `    ${html}`,
    `  </div>`,
    `</${tag}>`,
  ];
}

function buildBlock(html: string, entry: SSGEntry): string[] {
  const tag = entry.meta.tag ?? "div";
  const cls = entry.meta.class ?? "";

  return [
    "",
    `{%- doc -%}`,
    `  @name ${entry.meta.name}`,
    `  @context theme-block`,
    `{%- enddoc -%}`,
    "",
    "{% liquid",
    `  assign el_id = 'shopify-' | append: section.id | append: '-' | append: block.id`,
    "%}",
    "",
    `<${tag}`,
    `  id="{{ el_id }}"`,
    `  data-section-id="{{ section.id }}"`,
    `  data-ssg-component="${entry.kebabName}"`,
    cls ? `  class="${cls}"` : "",
    `  {{ block.shopify_attributes }}`,
    `>`,
    `  <div data-ssg-hydrate>`,
    `    ${html}`,
    `  </div>`,
    `</${tag}>`,
  ];
}

export function getOutputPath(
  entry: SSGEntry,
  options: {
    prefix: { template: string; section: string; block: string };
    outputName?: string;
    themeRoot: string;
  },
): string {
  const type = entry.meta.type ?? entry.targetType;
  const dirName = type === "block" ? "blocks" : `${type}s`;
  const fileName = resolveFileName(entry, type, options);
  return path.join(options.themeRoot, dirName, fileName);
}

import path from "node:path";

function resolveFileName(
  entry: SSGEntry,
  type: string,
  options: {
    prefix: { template: string; section: string; block: string };
    outputName?: string;
  },
): string {
  if (options.outputName) {
    return (
      options.outputName
        .replace(/\{type\}/g, type)
        .replace(/\{kebab\}/g, entry.kebabName)
        .replace(/\{pascal\}/g, entry.componentName)
        .replace(/\{target\}/g, entry.targetType) + ".liquid"
    );
  }

  const prefix = options.prefix[type as keyof typeof options.prefix] ?? "react-";
  return `${prefix}${entry.kebabName}.liquid`;
}
