/**
 * @file Liquid file assembler — builds the final `.liquid` output files.
 *
 * Takes the SSR-rendered HTML, entry metadata, CSS, script asset path,
 * tracked Liquid expressions, and registered Liquid blocks, then assembles
 * them into a complete Liquid template (section/block/snippet/template).
 *
 * Key responsibilities:
 * - Dispatch to `buildSection`, `buildBlock`, `buildSnippet` helpers.
 * - Inject Liquid blocks **before** the JSON bridge so that any Liquid
 *   variables defined by the blocks are available when the bridge serializes
 *   tracked expressions via the `| json` filter.
 * - Append inline CSS via `{% stylesheet %}` tags.
 * - Render shared CSS snippets via `{% render '...' %}`.
 * - Append the `<script type="module">` tag for client-side hydration.
 * - Append the Shopify setting schema via `{% schema %}` (sections/blocks only).
 */
import type { SSGEntry } from "../types/ssg";
import { generateSchema } from "./schema";
import { getAssetRelativePath } from "./liquid-paths";

/** Disclaimer comment injected at the top of every generated `.liquid` file. */
const DISCLAIMER =
  "{% comment %}\n  IMPORTANT: This file is automatically generated by vite-plugin-shopify.\n  Do not attempt to modify this file directly, as any changes will be overwritten by the next build.\n{% endcomment %}\n";

/** Options controlling Liquid file output naming and paths. */
export interface AssembleOptions {
  prefix: { template: string; section: string; block: string; snippet: string };
  outputName?: string;
  buildDir: string;
}

/**
 * Assembles a complete `.liquid` file from all constituent parts.
 *
 * Dispatch:
 * - `"template"` → raw HTML only (no wrapper).
 * - `"section"` → wrapper with section wrapper, JSON bridge, hydrate container.
 * - `"block"` → wrapper with block docs, `shopify_attributes`, JSON bridge.
 * - `"snippet"` → wrapper with minimal wrapper, no schema.
 * - Default → treated as a section.
 *
 * @param html               - SSR-rendered React HTML.
 * @param entry              - Entry metadata (name, type, settings schema, etc.).
 * @param scriptAsset        - Basename of the client-side JS bundle (or `null`).
 * @param cssContents        - Inline CSS strings and shared snippet names.
 * @param options            - Prefix/output naming configuration.
 * @param trackedExpressions - Liquid expressions to include in the JSON bridge.
 * @param liquidBlocks       - Raw Liquid code blocks injected before the bridge.
 * @returns The full `.liquid` file content as a string.
 */
export function assembleLiquidFile(
  html: string,
  entry: SSGEntry,
  scriptAsset: string | null,
  cssContents: { inline: string[]; snippets: string[] },
  options: AssembleOptions,
  trackedExpressions: string[] = [],
  liquidBlocks: string[] = [],
): string {
  const type = entry.meta.type ?? entry.targetType;
  const parts = [DISCLAIMER];

  // Liquid blocks are joined and injected before the JSON bridge so their
  // output (variables, assignments) is available for bridge serialization.
  const liquidPrepend = liquidBlocks.length > 0 ? liquidBlocks.join("\n") : "";

  switch (type) {
    case "template":
      parts.push(html);
      break;
    case "section":
      parts.push(...buildSection(html, entry, trackedExpressions, liquidPrepend));
      break;
    case "block":
      parts.push(...buildBlock(html, entry, trackedExpressions, liquidPrepend));
      break;
    case "snippet":
      parts.push(...buildSnippet(html, entry, trackedExpressions, liquidPrepend));
      break;
    default:
      parts.push(...buildSection(html, entry, trackedExpressions, liquidPrepend));
      break;
  }

  // Shared CSS snippets rendered via Liquid `{% render %}`
  for (const snippet of cssContents.snippets) {
    parts.push("", `{% render '${snippet}' %}`);
  }

  // Inline CSS via `<style>` or `{% stylesheet %}` (section/block-specific)
  if (cssContents.inline.length > 0) {
    parts.push(
      "",
      "{% stylesheet %}",
      ...cssContents.inline.map((c) => c.trim()),
      "{% endstylesheet %}",
    );
  }

  // Client-side hydration script
  if (scriptAsset) {
    const assetPath = getAssetRelativePath(options.buildDir, scriptAsset);
    parts.push(
      "",
      `<script type="module" src="{{ '${assetPath}' | asset_url }}"></script>`,
    );
  }

  // Shopify section/block settings schema (not needed for snippets)
  if (type !== "snippet") {
    parts.push(generateSchema(entry.meta));
  }

  return parts.join("\n") + "\n";
}

const hasBlocks = (entry: SSGEntry): boolean =>
  !!entry.meta.blocks && entry.meta.blocks.length > 0;

/**
 * Builds the JSON bridge (`<script type="application/json" data-ssg-liquid>`)
 * that passes resolved Liquid values to the client-side React app.
 *
 * Each tracked expression is serialized via Liquid's `| json` filter to produce
 * valid JSON. The resulting object is read by `LiquidDataContext` on the client.
 *
 * @param trackedExpressions - List of Liquid expression strings (e.g. `"section.settings.title"`).
 * @returns The HTML string for the JSON bridge, or an empty string if there are
 *   no tracked expressions.
 */
function buildLiquidBridge(trackedExpressions: string[]): string {
  if (trackedExpressions.length === 0) return "";

  const entries = trackedExpressions.map((expr, i) => {
    const comma = i < trackedExpressions.length - 1 ? "," : "";
    return `    "${expr}": {{ ${expr} | json }}${comma}`;
  });

  return [
    '  <script type="application/json" data-ssg-liquid>',
    "  {",
    entries.join("\n"),
    "  }",
    "  </script>",
  ].join("\n");
}

/**
 * Builds the HTML wrapper for a Shopify **section**.
 *
 * Structure:
 * ```
 * <tag id="{{ section.id }}" data-section-id="..." data-ssg-component="...">
 *   {liquidPrepend}
 *   {JSON bridge}
 *   <div data-ssg-hydrate>{SSR HTML}</div>
 *   {% content_for 'blocks' %}
 * </tag>
 * ```
 */
function buildSection(
  html: string,
  entry: SSGEntry,
  trackedExpressions: string[],
  liquidPrepend: string = "",
): string[] {
  const tag = entry.meta.tag ?? "div";
  const cls = entry.meta.class ?? "";

  const lines: string[] = [
    "",
    `<${tag}`,
    `  id="{{ section.id }}"`,
    `  data-section-id="{{ section.id }}"`,
    `  data-ssg-component="${entry.kebabName}"`,
  ];
  if (cls) lines.push(`  class="${cls}"`);
  lines.push(`>`);

  if (liquidPrepend) lines.push(liquidPrepend);

  const liquidBridge = buildLiquidBridge(trackedExpressions);
  if (liquidBridge) lines.push(liquidBridge);

  lines.push(
    `  <div data-ssg-hydrate>${html}</div>`,
  );

  if (hasBlocks(entry)) lines.push(`  {% content_for 'blocks' %}`);
  lines.push(`</${tag}>`);
  return lines;
}

/**
 * Builds the HTML wrapper for a Shopify **theme block**.
 *
 * Includes a `{%- doc -%}` block for theme block metadata and
 * `{{ block.shopify_attributes }}` for Shopify's block attribute injection.
 *
 * Structure:
 * ```
 * {%- doc -%}
 *   @name {entry.meta.name}
 *   @context theme-block
 * {%- enddoc -%}
 * <tag id="{{ block.id }}" ... {{ block.shopify_attributes }}>
 *   {liquidPrepend}
 *   {JSON bridge}
 *   <div data-ssg-hydrate>{SSR HTML}</div>
 * </tag>
 * ```
 */
function buildBlock(
  html: string,
  entry: SSGEntry,
  trackedExpressions: string[],
  liquidPrepend: string = "",
): string[] {
  const tag = entry.meta.tag ?? "div";
  const cls = entry.meta.class ?? "";

  const lines: string[] = [
    "",
    `{%- doc -%}`,
    `  @name ${entry.meta.name}`,
    `  @context theme-block`,
    `{%- enddoc -%}`,
    "",
    `<${tag}`,
    `  id="{{ block.id }}"`,
    `  data-section-id="{{ section.id }}"`,
    `  data-ssg-component="${entry.kebabName}"`,
  ];
  if (cls) lines.push(`  class="${cls}"`);
  lines.push(
    `  {{ block.shopify_attributes }}`,
    `>`,
  );

  if (liquidPrepend) lines.push(liquidPrepend);

  const liquidBridge = buildLiquidBridge(trackedExpressions);
  if (liquidBridge) lines.push(liquidBridge);

  lines.push(
    `  <div data-ssg-hydrate>${html}</div>`,
  );

  if (hasBlocks(entry)) lines.push(`  {% content_for 'blocks' %}`);
  lines.push(`</${tag}>`);
  return lines;
}

/**
 * Builds the HTML wrapper for a Shopify **snippet**.
 *
 * Snippets have a minimal wrapper — no section/block IDs, no schema, no
 * `{% content_for 'blocks' %}`. The SSR HTML is nested inside a
 * `<div data-ssg-hydrate>` for client-side hydration.
 */
function buildSnippet(
  html: string,
  entry: SSGEntry,
  trackedExpressions: string[],
  liquidPrepend: string = "",
): string[] {
  const lines: string[] = [
    "",
    `<div data-ssg-component="${entry.kebabName}">`,
  ];

  if (liquidPrepend) lines.push(liquidPrepend);

  const liquidBridge = buildLiquidBridge(trackedExpressions);
  if (liquidBridge) lines.push(liquidBridge);

  lines.push(
    `  <div data-ssg-hydrate>`,
    `    ${html}`,
    `  </div>`,
    `</div>`,
  );
  return lines;
}
