import type { SSGEntry } from "../types";
import { generateSchema } from "./schema-gen";

const DISCLAIMER =
  "{% comment %}\n  IMPORTANT: This file is automatically generated by vite-plugin-shopify.\n  Do not attempt to modify this file directly, as any changes will be overwritten by the next build.\n{% endcomment %}\n";

interface AssembleOptions {
  prefix: { template: string; section: string; block: string };
  outputName?: string;
  buildDir: string;
}

export function assembleLiquidFile(
  html: string,
  entry: SSGEntry,
  scriptAsset: string | null,
  cssContents: string[],
  options: AssembleOptions,
): string {
  const type = entry.meta.type ?? entry.targetType;
  const parts = [DISCLAIMER];

  switch (type) {
    case "template":
      parts.push(html);
      break;
    case "section":
      parts.push(...buildSection(html, entry));
      break;
    case "block":
      parts.push(...buildBlock(html, entry));
      break;
    default:
      parts.push(...buildSection(html, entry));
      break;
  }

  if (cssContents.length > 0) {
    parts.push(
      "",
      "{% stylesheet %}",
      ...cssContents.map((c) => c.trim()),
      "{% endstylesheet %}",
    );
  }

  if (scriptAsset) {
    const assetPath = getAssetRelativePath(options.buildDir, scriptAsset);
    parts.push(
      "",
      `<script type="module" src="{{ '${assetPath}' | asset_url }}"></script>`,
    );
  }

  parts.push(generateSchema(entry.meta));

  return parts.join("\n") + "\n";
}

const hasBlocks = (entry: SSGEntry): boolean =>
  !!entry.meta.blocks && entry.meta.blocks.length > 0;

const SETTINGS_SECTION = `  <script type="application/json" data-ssg-props>{{ section.settings | json }}</script>`;
const SETTINGS_BLOCK = `  <script type="application/json" data-ssg-props>{{ block.settings | json }}</script>`;

function buildSection(html: string, entry: SSGEntry): string[] {
  const tag = entry.meta.tag ?? "div";
  const cls = entry.meta.class ?? "";

  const lines: string[] = [
    "",
    `<${tag}`,
    `  id="{{ section.id }}"`,
    `  data-section-id="{{ section.id }}"`,
    `  data-ssg-component="${entry.kebabName}"`,
  ];
  if (cls) lines.push(`  class="${cls}"`);
  lines.push(
    `>`,
    SETTINGS_SECTION,
    `  <div data-ssg-hydrate>`,
    `    ${html}`,
    `  </div>`,
  );
  if (hasBlocks(entry)) lines.push(`  {% content_for 'blocks' %}`);
  lines.push(`</${tag}>`);
  return lines;
}

function buildBlock(html: string, entry: SSGEntry): string[] {
  const tag = entry.meta.tag ?? "div";
  const cls = entry.meta.class ?? "";

  const lines: string[] = [
    "",
    `{%- doc -%}`,
    `  @name ${entry.meta.name}`,
    `  @context theme-block`,
    `{%- enddoc -%}`,
    "",
    `<${tag}`,
    `  id="{{ block.id }}"`,
    `  data-section-id="{{ section.id }}"`,
    `  data-ssg-component="${entry.kebabName}"`,
  ];
  if (cls) lines.push(`  class="${cls}"`);
  lines.push(
    `  {{ block.shopify_attributes }}`,
    `>`,
    SETTINGS_BLOCK,
    `  <div data-ssg-hydrate>`,
    `    ${html}`,
    `  </div>`,
  );
  if (hasBlocks(entry)) lines.push(`  {% content_for 'blocks' %}`);
  lines.push(`</${tag}>`);
  return lines;
}

export function getOutputPath(
  entry: SSGEntry,
  options: {
    prefix: { template: string; section: string; block: string };
    outputName?: string;
    themeRoot: string;
  },
): string {
  const type = entry.meta.type ?? entry.targetType;
  const dirName = type === "block" ? "blocks" : `${type}s`;
  const fileName = resolveFileName(entry, type, options);
  return path.join(options.themeRoot, dirName, fileName);
}

import path from "node:path";

function getAssetRelativePath(buildDir: string, filename: string): string {
  if (!buildDir.startsWith("assets/")) return filename;
  const prefix = buildDir.slice("assets/".length);
  return prefix ? `${prefix}/${filename}` : filename;
}

function resolveFileName(
  entry: SSGEntry,
  type: string,
  options: {
    prefix: { template: string; section: string; block: string };
    outputName?: string;
  },
): string {
  if (options.outputName) {
    return (
      options.outputName
        .replace(/\{type\}/g, type)
        .replace(/\{kebab\}/g, entry.kebabName)
        .replace(/\{pascal\}/g, entry.componentName)
        .replace(/\{target\}/g, entry.targetType) + ".liquid"
    );
  }

  const prefix = options.prefix[type as keyof typeof options.prefix] ?? "react-";
  return `${prefix}${entry.kebabName}.liquid`;
}
