/**
 * @file Liquid file assembler — V2.6.
 *
 * Attribute names shortened, id/data-section-id removed.
 * Uses unified ShopifyContext.buildLiquidBridge for JSON bridge generation.
 */
import type { SSGEntry } from "../types/ssg";
import { generateSchema } from "./schema";
import { getAssetRelativePath } from "./liquid-paths";
import { ATTR_HYDRATE, ATTR_COMPONENT } from "../constants/attributes";
import { buildLiquidBridge, type TrackOptions } from "../runtime/bridge";
import { logger } from "../core/logger";

const log = logger("ssg:assembler");

function buildDisclaimer(source?: AssembleOptions["source"]): string {
  const lines = [
    "{% comment %}",
    "  IMPORTANT: This file is automatically generated by vite-plugin-react-shopify.",
    "  Do not modify this file directly; the next successful build will overwrite it.",
  ];
  if (source) {
    lines.push(`  Plugin: ${source.pluginVersion}`);
    lines.push(`  Source: ${source.path}`);
    lines.push(`  Source hash: ${source.hash}`);
  }
  lines.push("{% endcomment %}", "");
  return lines.join("\n");
}

export interface AssembleOptions {
  prefix: { template: string; section: string; block: string; snippet: string };
  outputName?: string;
  buildDir: string;
  /** Block script filenames to emit BEFORE the section script. */
  blockScripts?: string[];
  runtime?: "static" | "hydrate" | "client";
  source?: { path: string; hash: string; pluginVersion: string };
}

export function assembleLiquidFile(
  html: string,
  entry: SSGEntry,
  scriptAsset: string | null,
  cssContents: { inline: string[]; snippets: string[] },
  options: AssembleOptions,
  trackedExpressions: string[] = [],
  liquidBlocks: string[] = [],
  trackMap?: Map<string, TrackOptions>,
): string {
  const type = entry.targetType;
  const parts = [buildDisclaimer(options.source)];
  const runtime = options.runtime ?? (scriptAsset ? "hydrate" : "static");
  const moduleScripts = buildModuleScripts(entry, scriptAsset, options, runtime);

  const liquidPrepend = liquidBlocks.length > 0 ? liquidBlocks.join("\n") : "";

  switch (type) {
    case "template":
      parts.push(
        ...buildSnippet(html, entry, trackedExpressions, liquidPrepend, trackMap, runtime),
      );
      break;
    case "section":
      parts.push(
        ...buildSection(html, entry, trackedExpressions, liquidPrepend, trackMap, runtime),
      );
      break;
    case "block":
      parts.push(
        ...buildBlock(
          html,
          entry,
          trackedExpressions,
          liquidPrepend,
          trackMap,
          runtime,
          moduleScripts,
        ),
      );
      break;
    case "snippet":
      parts.push(
        ...buildSnippet(html, entry, trackedExpressions, liquidPrepend, trackMap, runtime),
      );
      break;
    default:
      parts.push(
        ...buildSection(html, entry, trackedExpressions, liquidPrepend, trackMap, runtime),
      );
      break;
  }

  for (const snippet of cssContents.snippets) {
    parts.push("", `{% render '${snippet}' %}`);
  }

  if (cssContents.inline.length > 0) {
    parts.push(
      "",
      "{% stylesheet %}",
      ...cssContents.inline.map((c) => c.trim()),
      "{% endstylesheet %}",
    );
  }

  if (type !== "block") {
    for (const script of moduleScripts) {
      parts.push("", script);
    }
  }

  if (type !== "snippet") {
    parts.push(generateSchema(entry.meta, type));
  }

  return parts.join("\n") + "\n";
}

function buildModuleScripts(
  entry: SSGEntry,
  scriptAsset: string | null,
  options: AssembleOptions,
  runtime: "static" | "hydrate" | "client",
): string[] {
  if (runtime === "static") return [];

  const scripts: string[] = [];

  // Block scripts go BEFORE the section script so block entry modules
  // register `ssg:blocks:ready` listeners before the section hydrates.
  if (options.blockScripts && options.blockScripts.length > 0) {
    log.debug(
      "%s: emitting %d block scripts before own script",
      entry.kebabName,
      options.blockScripts.length,
    );
    for (const bs of options.blockScripts) {
      const assetPath = getAssetRelativePath(options.buildDir, bs);
      scripts.push(`<script type="module" src="{{ '${assetPath}' | asset_url }}"></script>`);
    }
  }

  if (scriptAsset) {
    const assetPath = getAssetRelativePath(options.buildDir, scriptAsset);
    scripts.push(`<script type="module" src="{{ '${assetPath}' | asset_url }}"></script>`);
  }

  return scripts;
}

function resolveLiquidBridge(
  trackedExpressions: string[],
  trackMap?: Map<string, TrackOptions>,
): string {
  if (trackMap && trackMap.size > 0) {
    return buildLiquidBridge(trackMap);
  }
  // Legacy fallback: old hooks populate GW_TRACK but not GW_TRACK_MAP
  if (trackedExpressions.length > 0) {
    const entries = trackedExpressions.map((expr, i) => {
      const comma = i < trackedExpressions.length - 1 ? "," : "";
      return `    ${JSON.stringify(expr)}: {{ ${expr} | json }}${comma}`;
    });
    return [
      '  <script type="application/json" data-ssg-liquid>',
      "  {",
      entries.join("\n"),
      "  }",
      "  </script>",
    ].join("\n");
  }
  return "";
}

function buildSection(
  html: string,
  entry: SSGEntry,
  trackedExpressions: string[],
  liquidPrepend: string = "",
  trackMap?: Map<string, TrackOptions>,
  runtime: "static" | "hydrate" | "client" = "static",
): string[] {
  if (runtime === "static") {
    return ["", ...(liquidPrepend ? [liquidPrepend] : []), html];
  }

  const lines: string[] = ["", `<div`];
  lines.push(`  ${ATTR_COMPONENT}="${entry.id}"`);
  lines.push(`>`);

  if (liquidPrepend) lines.push(liquidPrepend);

  const liquidBridge = resolveLiquidBridge(trackedExpressions, trackMap);
  if (liquidBridge) lines.push(liquidBridge);

  lines.push(`  <div ${ATTR_HYDRATE}>${html}</div>`);

  // BlockSlot is now a React component rendered inside the SSR HTML.
  // No need to auto-inject a `<shopify-block-slot>` sibling — the React
  // tree declares the slot location explicitly.
  lines.push(`</div>`);
  return lines;
}

function buildBlock(
  html: string,
  entry: SSGEntry,
  trackedExpressions: string[],
  liquidPrepend: string = "",
  trackMap?: Map<string, TrackOptions>,
  runtime: "static" | "hydrate" | "client" = "static",
  moduleScripts: string[] = [],
): string[] {
  const ownsWrapper = entry.meta.tag == null;
  if (runtime === "static" && !ownsWrapper) {
    return ["", ...(liquidPrepend ? [liquidPrepend] : []), html];
  }

  const tag = "div";
  const cls = entry.meta.class ?? "";

  const lines: string[] = [
    "",
    `{%- doc -%}`,
    `  @name ${entry.meta.name}`,
    `  @context theme-block`,
    `{%- enddoc -%}`,
    "",
    `<${tag}`,
  ];
  if (ownsWrapper) {
    lines.push(`  id="{{ block.id }}"`);
    if (cls) lines.push(`  class="${cls}"`);
    lines.push(`  {{ block.shopify_attributes }}`);
  }
  if (runtime !== "static") lines.push(`  ${ATTR_COMPONENT}="${entry.id}"`);
  lines.push(`>`);

  if (liquidPrepend) lines.push(liquidPrepend);

  if (runtime !== "static") {
    const liquidBridge = resolveLiquidBridge(trackedExpressions, trackMap);
    if (liquidBridge) lines.push(liquidBridge);
    lines.push(`  <div ${ATTR_HYDRATE}>${html}</div>`);
  } else {
    lines.push(html);
  }

  for (const script of moduleScripts) {
    lines.push(`  ${script}`);
  }

  lines.push(`</${tag}>`);
  return lines;
}

function buildSnippet(
  html: string,
  entry: SSGEntry,
  trackedExpressions: string[],
  liquidPrepend: string = "",
  trackMap?: Map<string, TrackOptions>,
  runtime: "static" | "hydrate" | "client" = "static",
): string[] {
  if (runtime === "static") {
    return ["", ...(liquidPrepend ? [liquidPrepend] : []), html];
  }

  const lines: string[] = ["", `<div ${ATTR_COMPONENT}="${entry.id}">`];

  if (liquidPrepend) lines.push(liquidPrepend);

  const liquidBridge = resolveLiquidBridge(trackedExpressions, trackMap);
  if (liquidBridge) lines.push(liquidBridge);

  lines.push(`  <div ${ATTR_HYDRATE}>`, `    ${html}`, `  </div>`, `</div>`);
  return lines;
}
