import { resolve } from "node:path";
import type { SSGEntry } from "../types";
import { generateSchema } from "./schema-gen";

const DISCLAIMER =
  "{% comment %}\n  IMPORTANT: This file is automatically generated by vite-plugin-shopify SSG.\n  Do not attempt to modify this file directly, as any changes will be overwritten by the next build.\n{% endcomment %}\n";

interface AssembleOptions {
  prefix: { template?: string; section?: string; block?: string };
  outputName?: string;
  sourceCodeDir: string;
}

export function assembleLiquidFile(
  html: string,
  entry: SSGEntry,
  options: AssembleOptions,
): string {
  const type = entry.meta.type ?? entry.targetType;
  const hydrateEntryRef = `_ssg-hydrate/${entry.kebabName}.tsx`;

  switch (type) {
    case "template":
      return assembleTemplate(html, hydrateEntryRef);
    case "section":
      return assembleSection(html, entry, hydrateEntryRef);
    case "block":
      return assembleBlock(html, entry, hydrateEntryRef);
    default:
      return assembleSection(html, entry, hydrateEntryRef);
  }
}

function assembleTemplate(html: string, hydrateEntryRef: string): string {
  return [DISCLAIMER, html, `{% render 'vite-tag', entry: '${hydrateEntryRef}' %}`].join("\n");
}

function assembleSection(html: string, entry: SSGEntry, hydrateEntryRef: string): string {
  return [
    DISCLAIMER,
    "",
    "{% liquid",
    `  assign el_id = 'shopify-' | append: section.id`,
    "%}",
    "",
    buildSectionRoot(html, "{{ el_id }}", entry),
    "",
    `{% render 'vite-tag', entry: '${hydrateEntryRef}' %}`,
    generateSchema(entry.meta),
  ].join("\n");
}

function assembleBlock(html: string, entry: SSGEntry, hydrateEntryRef: string): string {
  return [
    DISCLAIMER,
    "",
    `{%- doc -%}`,
    `  @name ${entry.meta.name}`,
    `  @context theme-block`,
    `{%- enddoc -%}`,
    "",
    "{% liquid",
    `  assign el_id = 'shopify-' | append: section.id | append: '-' | append: block.id`,
    "%}",
    "",
    buildBlockRoot(html, "{{ el_id }}", entry),
    "",
    `{% render 'vite-tag', entry: '${hydrateEntryRef}' %}`,
    generateSchema(entry.meta),
  ].join("\n");
}

function buildSectionRoot(html: string, elId: string, entry: SSGEntry): string {
  const tag = entry.meta.tag ?? "div";
  const cls = entry.meta.class ?? "";

  return [
    `<${tag}`,
    `  id="${elId}"`,
    `  data-section-id="{{ section.id }}"`,
    cls ? `  class="${cls}"` : "",
    `>`,
    `  ${html}`,
    `</${tag}>`,
  ]
    .filter(Boolean)
    .join("\n");
}

function buildBlockRoot(html: string, elId: string, entry: SSGEntry): string {
  const tag = entry.meta.tag ?? "div";
  const cls = entry.meta.class ?? "";

  return [
    `<${tag}`,
    `  id="${elId}"`,
    `  data-section-id="{{ section.id }}"`,
    cls ? `  class="${cls}"` : "",
    `  {{ block.shopify_attributes }}`,
    `>`,
    `  ${html}`,
    `</${tag}>`,
  ]
    .filter(Boolean)
    .join("\n");
}

export function getOutputPath(
  entry: SSGEntry,
  options: {
    prefix: { template?: string; section?: string; block?: string };
    outputName?: string;
    themeRoot: string;
  },
): string {
  const type = entry.meta.type ?? entry.targetType;
  const dirName = type === "block" ? "blocks" : `${type}s`;
  const fileName = resolveFileName(entry, type, options);

  return resolve(options.themeRoot, dirName, fileName);
}

function resolveFileName(
  entry: SSGEntry,
  type: string,
  options: { prefix: { template?: string; section?: string; block?: string }; outputName?: string },
): string {
  if (options.outputName) {
    return (
      options.outputName
        .replace(/\{type\}/g, type)
        .replace(/\{kebab\}/g, entry.kebabName)
        .replace(/\{pascal\}/g, entry.componentName)
        .replace(/\{target\}/g, entry.targetType) + ".liquid"
    );
  }

  const prefix = (options.prefix as Record<string, string>)[type] ?? "section.react-";
  return `${prefix}${entry.kebabName}.liquid`;
}
