import type { SSGEntry } from "../types/ssg";
import { generateSchema } from "./schema";
import { getAssetRelativePath } from "./liquid-paths";

const DISCLAIMER =
  "{% comment %}\n  IMPORTANT: This file is automatically generated by vite-plugin-shopify.\n  Do not attempt to modify this file directly, as any changes will be overwritten by the next build.\n{% endcomment %}\n";

export interface AssembleOptions {
  prefix: { template: string; section: string; block: string; snippet: string };
  outputName?: string;
  buildDir: string;
}

export function assembleLiquidFile(
  html: string,
  entry: SSGEntry,
  scriptAsset: string | null,
  cssContents: { inline: string[]; snippets: string[] },
  options: AssembleOptions,
  trackedExpressions: string[] = [],
  liquidBlocks: string[] = [],
): string {
  const type = entry.meta.type ?? entry.targetType;
  const parts = [DISCLAIMER];
  const liquidPrepend = liquidBlocks.length > 0 ? liquidBlocks.join("\n") : "";

  switch (type) {
    case "template":
      parts.push(html);
      break;
    case "section":
      parts.push(...buildSection(html, entry, trackedExpressions, liquidPrepend));
      break;
    case "block":
      parts.push(...buildBlock(html, entry, trackedExpressions, liquidPrepend));
      break;
    case "snippet":
      parts.push(...buildSnippet(html, entry, trackedExpressions, liquidPrepend));
      break;
    default:
      parts.push(...buildSection(html, entry, trackedExpressions, liquidPrepend));
      break;
  }

  for (const snippet of cssContents.snippets) {
    parts.push("", `{% render '${snippet}' %}`);
  }

  if (cssContents.inline.length > 0) {
    parts.push(
      "",
      "{% stylesheet %}",
      ...cssContents.inline.map((c) => c.trim()),
      "{% endstylesheet %}",
    );
  }

  if (scriptAsset) {
    const assetPath = getAssetRelativePath(options.buildDir, scriptAsset);
    parts.push(
      "",
      `<script type="module" src="{{ '${assetPath}' | asset_url }}"></script>`,
    );
  }

  if (type !== "snippet") {
    parts.push(generateSchema(entry.meta));
  }

  return parts.join("\n") + "\n";
}

const hasBlocks = (entry: SSGEntry): boolean =>
  !!entry.meta.blocks && entry.meta.blocks.length > 0;

function buildLiquidBridge(trackedExpressions: string[]): string {
  if (trackedExpressions.length === 0) return "";

  const entries = trackedExpressions.map((expr, i) => {
    const comma = i < trackedExpressions.length - 1 ? "," : "";
    return `    "${expr}": {{ ${expr} | json }}${comma}`;
  });

  return [
    '  <script type="application/json" data-ssg-liquid>',
    "  {",
    entries.join("\n"),
    "  }",
    "  </script>",
  ].join("\n");
}

function buildSection(
  html: string,
  entry: SSGEntry,
  trackedExpressions: string[],
  liquidPrepend: string = "",
): string[] {
  const tag = entry.meta.tag ?? "div";
  const cls = entry.meta.class ?? "";

  const lines: string[] = [
    "",
    `<${tag}`,
    `  id="{{ section.id }}"`,
    `  data-section-id="{{ section.id }}"`,
    `  data-ssg-component="${entry.kebabName}"`,
  ];
  if (cls) lines.push(`  class="${cls}"`);
  lines.push(`>`);

  if (liquidPrepend) lines.push(liquidPrepend);

  const liquidBridge = buildLiquidBridge(trackedExpressions);
  if (liquidBridge) lines.push(liquidBridge);

  lines.push(
    `  <div data-ssg-hydrate>${html}</div>`,
  );

  if (hasBlocks(entry)) lines.push(`  {% content_for 'blocks' %}`);
  lines.push(`</${tag}>`);
  return lines;
}

function buildBlock(
  html: string,
  entry: SSGEntry,
  trackedExpressions: string[],
  liquidPrepend: string = "",
): string[] {
  const tag = entry.meta.tag ?? "div";
  const cls = entry.meta.class ?? "";

  const lines: string[] = [
    "",
    `{%- doc -%}`,
    `  @name ${entry.meta.name}`,
    `  @context theme-block`,
    `{%- enddoc -%}`,
    "",
    `<${tag}`,
    `  id="{{ block.id }}"`,
    `  data-section-id="{{ section.id }}"`,
    `  data-ssg-component="${entry.kebabName}"`,
  ];
  if (cls) lines.push(`  class="${cls}"`);
  lines.push(
    `  {{ block.shopify_attributes }}`,
    `>`,
  );

  if (liquidPrepend) lines.push(liquidPrepend);

  const liquidBridge = buildLiquidBridge(trackedExpressions);
  if (liquidBridge) lines.push(liquidBridge);

  lines.push(
    `  <div data-ssg-hydrate>${html}</div>`,
  );

  if (hasBlocks(entry)) lines.push(`  {% content_for 'blocks' %}`);
  lines.push(`</${tag}>`);
  return lines;
}

function buildSnippet(
  html: string,
  entry: SSGEntry,
  trackedExpressions: string[],
  liquidPrepend: string = "",
): string[] {
  const lines: string[] = [
    "",
    `<div data-ssg-component="${entry.kebabName}">`,
  ];

  if (liquidPrepend) lines.push(liquidPrepend);

  const liquidBridge = buildLiquidBridge(trackedExpressions);
  if (liquidBridge) lines.push(liquidBridge);

  lines.push(
    `  <div data-ssg-hydrate>`,
    `    ${html}`,
    `  </div>`,
    `</div>`,
  );
  return lines;
}
